service: house-crawling

provider:
  name: aws
  stage: dev
  runtime: python3.8
  region: eu-central-1
  # https://serverless-stack.com/chapters/configure-multiple-aws-profiles.html
  # profile: youngAccount
  role: arn:aws:iam::865878227404:role/service-role/house_crawling-role-ygbbbfya
  # environment:
  #   SHEET_KEY: ${env:SHEET_KEY}

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  get_joke:
    handler: handler.get_joke
    events:
      - http:
          path: joke
          method: get
  crawler:
    handler: main.crawl_all
    events:
      - http:
          path: main
          method: get

plugins:
  - serverless-prune-plugin
  - serverless-python-requirements
custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: non-linux
    slim: true